### ISSUE TITLE
[PE-D] Confusing instructions in features

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-1/tp#241]
As a user, why would I enter the same thing more than once? Don't think this should be in a UG

![image.png](https://raw.githubusercontent.com/ngnigel99/ped/main/files/f4e139f1-2122-45e8-80b2-cb82b11de16e.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ngnigel99/ped#2

**Comment by RemusTeo** [comment]
Hi, we did this because we referenced and follow AB3 UG. style You may refer to the features section.
![image](https://user-images.githubusercontent.com/28041798/139678028-d57e5c89-ff87-4778-b5a0-01a7d4a384db.png)

https://se-education.org/addressbook-level3/UserGuide.html
