### ISSUE TITLE
[PE-D] Suggestion for archive/ saving data

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-1/tp#269]
Not a big issue, but it'll be great to archive the entries (orders/ prescriptions) automatically to the text files. Additionally, no error message  is thrown when there are no entries found on a certain day. 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: ngnigel99/ped#6

**Comment by RemusTeo** [comment]
Thanks for the review. 
There actually already is automatic saving of data to text file implemented as every operation that modifies the data will dynamically be updated in data storage files. Archiving is just another side feature to transfer entries from current records to another different static file for archiving purposes.
I do agree with you on the point mentioned to throw error message when no entries are found. May consider implementing that if time permits. Thanks!
