### ISSUE TITLE
Issue of gradle checkstyle wrapped indentation

### ISSUE THREAD

**Issue by RemusTeo** [AY2122S1-CS2113T-T10-1/tp#46]
Currently gradle throwing error when wrapped indentation is 8 spaces (Java Coding Standard) for array initialization. Likely need to modify gradle checkstyle. To consult TA/Prof for advice first before trying to fix issue.

**Comment by alvintan01** [comment]
Opened an issue in the forum: https://github.com/nus-cs2113-AY2122S1/forum/issues/104
